### ISSUE TITLE
Error after updating laravel via composer ..

### ISSUE THREAD

**Issue by zaherg** [jasonlewis/enhanced-router#10]
hey,
today after updating laravel i got this problem which is :
"findPatternFilters() should be compatible with Illuminate\Routing\Router::findPatternFilters($method, $path)" ..
and here is the error message :

```
{"error":{"type":"ErrorException","message":"Declaration of JasonLewis\\EnhancedRouter\\Router::findPatternFilters() should be compatible with Illuminate\\Routing\\Router::findPatternFilters($method, $path)","file":"\/Users\/Zaher\/Sites\/klass\/vendor\/jasonlewis\/enhanced-router\/src\/JasonLewis\/EnhancedRouter\/Router.php","line":8}}
```

**Comment by zaherg** [comment]
its look like they have updated some of the core here : https://github.com/laravel/framework/commit/9d63918771902bd1d750988a93ee7981149523c0

**Comment by matthewscalf** [comment]
Is there a way to force a specific version that did work until there is a fix released for this?

**Comment by zaherg** [comment]
no problem all i have to do is to use the master ..

**Comment by matthewscalf** [comment]
You mean the master branch of laravel?

**Comment by zaherg** [comment]
yes ..

**Comment by asyakin** [comment]
public function findPatternFilters($method, $path)  {
    $filters = parent::findPatternFilters($method, $path);
    foreach ($this->httpVerbFilters as $verb => $values) {
        if ($verb == $method) {
            $filters = array_merge($filters, $values);
    }
    }
    return $filters;
}

**Comment by petraeus** [comment]
can somebody commit this update to the repo?

**Comment by jasonlewis** [comment]
Hey guys I'm back on the internet. Will push a fix for this shortly.

**Comment by baze** [comment]
I have the same problem with laravel 4.0.6 again:
Declaration of JasonLewis\EnhancedRouter\Router::findPatternFilters() should be compatible with Illuminate\Routing\Router::findPatternFilters($method, $path)

**Comment by jasonlewis** [comment]
This might have been because I removed the 1.0.3 tag due to some confusion. I've just re-tagged it so you should hopefully pull in the latest version now with a `composer update`.
