### ISSUE TITLE
Allow for header based route groups

### ISSUE THREAD

**Issue by lucadegasperi** [jasonlewis/enhanced-router#14]
I know it's sunday,

Since this package enhances the routing in a powerful way, why not enhance them even more?

I would love to be able to route to a different group based on the http headers sent by the client. do you think it's possible? My use case is the versioning of an API. Using headers would be more in line with the hateoas recommendations.

**Comment by jasonlewis** [comment]
I was actually working on an API package which would provide this sort of functionality. Hopefully in the coming weeks (possibly even the new year) I'll be working on code once more. At this stage I have no plan to implement anything further into this package.
