### ISSUE TITLE
Allow dynamic subdomain routing

### ISSUE THREAD

**Issue by Itrulia** [jasonlewis/enhanced-router#15]
What I would like to see is dynamic subdomain routing as an example:

``` php
Route::group(array('subdomain' => 'example'), function()
{

});
```

which would respond to: `example.domain.com` or `example.localhost` and so on...

**Comment by tlgreg** [comment]
Can't try now, but this doesn't work?

``` php
Route::group(array('domain' => 'example{domain}'), function() {});
```

**Comment by jasonlewis** [comment]
Yeah what @tlgreg has shown should work. Let us know.

**Comment by Itrulia** [comment]
I will try it ASAP
