### ISSUE TITLE
Enhance Router breaks URL::action() ?

### ISSUE THREAD

**Issue by joshuastine** [jasonlewis/enhanced-router#6]
It seems when I try to do reverse routing with the enhanced controller that my actions can't be found.  Is there a way around this?  It's also breaking my unit testing when I try to $this->call();  Thanks!

**Comment by jasonlewis** [comment]
Can you show me the code you're using. Are you using a route group with a prefix or a domain?

**Comment by joshuastine** [comment]
I was using a prefix.  But, I tried to replicate the error with a fresh
install and I can't so there must be a conflict with something else.  It's
weird, I get 'action' does not exist with my links when using the enhanced
router, but everything's fine when I comment out the provider.  As well, in
a similar set up in the fresh install everything works fine.  Please close
the issue for now and I'll let update if I'm able to reproduce the error.

Regards,
Josh
